import '../State_manage/Cubits/cubit.dart';

late final String? selectedUserID;
double? doubleselectedUserID  ;
String? StringselectedUserID ;
String? patientcode;
String? Doctorname ;
String? patientname ;
int? ClinicID ;
String? Book ;
String? SDATE ;
String? rowguid ;
String? Date  ;
String? Contact ;
String? DayType ;
String? time ;
String? selectedNo;
late bool    New  ;
bool?   edit ;
 bool isExpanded =false ;
 bool iscollabsed =false ;
DateTime initialDate2=DateTime.now();
DateTime ?selectedDate ;
 bool isDarkmodesaved =false  ;
 bool isArabicsaved =true  ;
 bool isArabic =false  ;
bool isDarkmode= false ;
late int docslenth;
late bool serviceonly ;
late int reservationslenth;
final String DateNow= "${DateTime.now()}";